//create message constants
const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

//get single message constants
const GET_SINGLE_MESSAGE_REQUEST = "GET_SINGLE_MESSAGE_REQUEST";
const GET_SINGLE_MESSAGE_SUCCESS = "GET_SINGLE_MESSAGE_SUCCESS";
const GET_SINGLE_MESSAGE_FAIL = "GET_SINGLE_MESSAGE_FAIL";

//get messages constants
const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";

//get user convos constants
const GET_USER_CONVOS_REQUEST = "GET_USER_CONVOS_REQUEST";
const GET_USER_CONVOS_SUCCESS = "GET_USER_CONVOS_SUCCESS";
const GET_USER_CONVOS_FAIL = "GET_MEUSER_CONVOSAIL";

//update message constants
const UPDATE_MESSAGE_REQUEST = "UPDATE_MESSAGE_REQUEST";
const UPDATE_MESSAGE_SUCCESS = "UPDATE_MESSAGE_SUCCESS";
const UPDATE_MESSAGE_FAIL = "UPDATE_MESSAGE_FAIL";

//delete MESSAGE constants
const DELETE_MESSAGE_REQUEST = "GET_MESSAGE_REQUEST";
const DELETE_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
const DELETE_MESSAGE_FAIL = "GET_MESSAGE_FAIL";

export {
  CREATE_MESSAGE_FAIL,
  CREATE_MESSAGE_REQUEST,
  CREATE_MESSAGE_SUCCESS,
  GET_SINGLE_MESSAGE_SUCCESS,
  GET_SINGLE_MESSAGE_REQUEST,
  GET_SINGLE_MESSAGE_FAIL,
  GET_MESSAGES_SUCCESS,
  GET_MESSAGES_REQUEST,
  GET_MESSAGES_FAIL,
  GET_USER_CONVOS_FAIL,
  GET_USER_CONVOS_REQUEST,
  GET_USER_CONVOS_SUCCESS,
  UPDATE_MESSAGE_FAIL,
  UPDATE_MESSAGE_REQUEST,
  UPDATE_MESSAGE_SUCCESS,
  DELETE_MESSAGE_FAIL,
  DELETE_MESSAGE_REQUEST,
  DELETE_MESSAGE_SUCCESS,
};
