//get metiers constants
const GET_METIERS_REQUEST = "GET_METIERS_REQUEST";
const GET_METIERS_SUCCESS = "GET_METIERS_SUCCESS";
const GET_METIERS_FAIL = "GET_METIERS_FAIL";

//get metiers constants
const GET_METIERS_USERS_REQUEST = "GET_METIERS_USERS_REQUEST";
const GET_METIERS_USERS_SUCCESS = "GET_METIERS_USERS_SUCCESS";
const GET_METIERS_USERS_FAIL = "GET_METIERS_USERS_FAIL";

//get single metiers constants
const GET_SINGLE_METIERS_REQUEST = "GET_SINGLE_METIERS_REQUEST";
const GET_SINGLE_METIERS_SUCCESS = "GET_SINGLE_METIERS_SUCCESS";
const GET_SINGLE_METIERS_FAIL = "GET_SINGLE_METIERS_FAIL";

//get metiers constants
const SEARCH_PARENT_REQUEST = "SEARCH_PARENT_REQUEST";
const SEARCH_PARENT_SUCCESS = "SEARCH_PARENT_SUCCESS";
const SEARCH_PARENT_FAIL = "SEARCH_PARENT_FAIL";

//add metiers constants
const ADD_METIERS_REQUEST = "ADD_METIERS_REQUEST";
const ADD_METIERS_SUCCESS = "ADD_METIERS_SUCCESS";
const ADD_METIERS_FAIL = "ADD_METIERS_FAIL";

//update users constants
const UPDATE_METIERS_REQUEST = "UPDATE_METIERS_REQUEST";
const UPDATE_METIERS_SUCCESS = "UPDATE_METIERS_SUCCESS";
const UPDATE_METIERS_FAIL = "UPDATE_METIERS_FAIL";

//DELETE users constants
const DELETE_METIERS_REQUEST = "DELETE_METIERS_REQUEST";
const DELETE_METIERS_SUCCESS = "DELETE_METIERS_SUCCESS";
const DELETE_METIERS_FAIL = "DELETE_METIERS_FAIL";

export {
  GET_METIERS_FAIL,
  GET_METIERS_REQUEST,
  GET_METIERS_SUCCESS,
  GET_SINGLE_METIERS_FAIL,
  GET_METIERS_USERS_FAIL,
  GET_METIERS_USERS_REQUEST,
  GET_METIERS_USERS_SUCCESS,
  GET_SINGLE_METIERS_REQUEST,
  GET_SINGLE_METIERS_SUCCESS,
  SEARCH_PARENT_FAIL,
  SEARCH_PARENT_REQUEST,
  SEARCH_PARENT_SUCCESS,
  ADD_METIERS_FAIL,
  ADD_METIERS_REQUEST,
  ADD_METIERS_SUCCESS,
  UPDATE_METIERS_FAIL,
  UPDATE_METIERS_REQUEST,
  UPDATE_METIERS_SUCCESS,
  DELETE_METIERS_FAIL,
  DELETE_METIERS_REQUEST,
  DELETE_METIERS_SUCCESS,
};
