//add realisations constants
const ADD_REALS_REQUEST = "ADD_REALS_REQUEST";
const ADD_REALS_SUCCESS = "ADD_REALS_SUCCESS";
const ADD_REALS_FAIL = "ADD_REALS_FAIL";

//get realisations constants
const GET_REALS_REQUEST = "GET_REALS_REQUEST";
const GET_REALS_SUCCESS = "GET_REALS_SUCCESS";
const GET_REALS_FAIL = "GET_REALS_FAIL";

//DELETE users single realisation
const DELETE_REALS_REQUEST = "DELETE_REALS_REQUEST";
const DELETE_REALS_SUCCESS = "DELETE_REALS_SUCCESS";
const DELETE_REALS_FAIL = "DELETE_REALS_FAIL";

export {
  GET_REALS_FAIL,
  GET_REALS_REQUEST,
  GET_REALS_SUCCESS,
  ADD_REALS_FAIL,
  ADD_REALS_REQUEST,
  ADD_REALS_SUCCESS,
  DELETE_REALS_FAIL,
  DELETE_REALS_REQUEST,
  DELETE_REALS_SUCCESS,
};
