//get metiers constants
const GET_TRAVAUX_REQUEST = "GET_TRAVAUX_REQUEST";
const GET_TRAVAUX_SUCCESS = "GET_TRAVAUX_SUCCESS";
const GET_TRAVAUX_FAIL = "GET_TRAVAUX_FAIL";

//add metiers constants
const ADD_TRAVAUX_REQUEST = "ADD_TRAVAUX_REQUEST";
const ADD_TRAVAUX_SUCCESS = "ADD_TRAVAUX_SUCCESS";
const ADD_TRAVAUX_FAIL = "ADD_TRAVAUX_FAIL";

//update users constants
const UPDATE_TRAVAUX_REQUEST = "UPDATE_TRAVAUX_REQUEST";
const UPDATE_TRAVAUX_SUCCESS = "UPDATE_TRAVAUX_SUCCESS";
const UPDATE_TRAVAUX_FAIL = "UPDATE_TRAVAUX_FAIL";

//DELETE users constants
const DELETE_TRAVAUX_REQUEST = "DELETE_TRAVAUX_REQUEST";
const DELETE_TRAVAUX_SUCCESS = "DELETE_TRAVAUX_SUCCESS";
const DELETE_TRAVAUX_FAIL = "DELETE_TRAVAUX_FAIL";

export {
  GET_TRAVAUX_FAIL,
  GET_TRAVAUX_REQUEST,
  GET_TRAVAUX_SUCCESS,
  ADD_TRAVAUX_FAIL,
  ADD_TRAVAUX_REQUEST,
  ADD_TRAVAUX_SUCCESS,
  UPDATE_TRAVAUX_FAIL,
  UPDATE_TRAVAUX_REQUEST,
  UPDATE_TRAVAUX_SUCCESS,
  DELETE_TRAVAUX_FAIL,
  DELETE_TRAVAUX_REQUEST,
  DELETE_TRAVAUX_SUCCESS,
};
